
version: '3'
services:
  product-service:
    build:
      context: ./product-service
    ports:
      - "3001:3000"
  user-service:
    build:
      context: ./user-service
    ports:
      - "3002:3000"
  payment-service:
    build:
      context: ./payment-service
    ports:
      - "3003:3000"
  trend-service:
    build:
      context: ./trend-service
    ports:
      - "3004:3000"
